force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SageRecId__c.field-meta.xml
<CustomField>
    <fullName>SageRecId__c</fullName>
    <externalId>true</externalId>
    <label>Sage Rec Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inntact_GL_Account__c/Inntact_GL_Account__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Entry__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Entry__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Restrictions__c</fullName>
    <label>Restrictions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10008</fullName>
                <label>General Unrestricted</label>
            </value>
            <value>
                <fullName>10007</fullName>
                <label>Reserve - Annual Meeting</label>
            </value>
            <value>
                <fullName>10006</fullName>
                <label>Reserve - Building</label>
            </value>
            <value>
                <fullName>10005</fullName>
                <label>Reserve - Operations Restricted</label>
            </value>
            <value>
                <fullName>10004</fullName>
                <label>Reserve - Operations Unrestricted</label>
            </value>
            <value>
                <fullName>10003</fullName>
                <label>Reserve - Technology</label>
            </value>
            <value>
                <fullName>10002</fullName>
                <label>With Donor Restriction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/Invoice_Entry__c.object-meta.xml
<CustomObject>
    <label>Invoice Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Invoice Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Entry__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <label>GL Account</label>
    <referenceTo>Inntact_GL_Account__c</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Payment__c/Invoice_Payment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP-{MM}{YYYY}{00}</displayFormat>
        <label>Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Payment__c/fields/SageRecId__c.field-meta.xml
<CustomField>
    <fullName>SageRecId__c</fullName>
    <externalId>true</externalId>
    <label>Sage Rec Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mulesoft_Connector__mdt/Mulesoft_Connector__mdt.object-meta.xml
<CustomObject>
    <label>Mulesoft Connector</label>
    <pluralLabel>Mulesoft Connectors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mulesoft_Connector__mdt/fields/LastCalloutDate__c.field-meta.xml
<CustomField>
    <fullName>LastCalloutDate__c</fullName>
    <label>Last Callout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>The Council of State Governments</label>
            </value>
            <value>
                <fullName>AAPCA</fullName>
                <label>The Association of Air Pollution Control</label>
            </value>
            <value>
                <fullName>APPA</fullName>
                <label>American Probation and Parole Association</label>
            </value>
            <value>
                <fullName>CANNRA</fullName>
                <label>Cannabis Regulators Association</label>
            </value>
            <value>
                <fullName>East</fullName>
                <label>East Region</label>
            </value>
            <value>
                <fullName>JC</fullName>
                <label>Justice Center</label>
            </value>
            <value>
                <fullName>MIC3</fullName>
                <label>Military Interstate Children&apos;s Compact C</label>
            </value>
            <value>
                <fullName>Midwest</fullName>
                <label>Midwest Region</label>
            </value>
            <value>
                <fullName>NASFA</fullName>
                <label>National Association of ST Facility Adm</label>
            </value>
            <value>
                <fullName>NASPE</fullName>
                <label>National Association of ST Pers Exec</label>
            </value>
            <value>
                <fullName>NASPTD</fullName>
                <label>National Association of ST Tech Director</label>
            </value>
            <value>
                <fullName>NATL</fullName>
                <label>National</label>
            </value>
            <value>
                <fullName>NATL HQ</fullName>
                <label>National Headquarters</label>
            </value>
            <value>
                <fullName>NEMA</fullName>
                <label>National Emergency Mgmt Association</label>
            </value>
            <value>
                <fullName>NHCSL</fullName>
                <label>National Hispanic Caucus of ST Legis</label>
            </value>
            <value>
                <fullName>SIDO</fullName>
                <label>State International Development Orgs</label>
            </value>
            <value>
                <fullName>South</fullName>
                <label>South Region</label>
            </value>
            <value>
                <fullName>West</fullName>
                <label>West Region</label>
            </value>
            <value>
                <fullName>WIG</fullName>
                <label>Women in Government</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <label>Project Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Restrictions__c</fullName>
    <label>Restrictions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Restrictions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SageRecId__c.field-meta.xml
<CustomField>
    <fullName>SageRecId__c</fullName>
    <externalId>true</externalId>
    <label>Sage Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Restrictions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10008</fullName>
        <label>General Unrestricted</label>
    </customValue>
    <customValue>
        <fullName>10007</fullName>
        <label>Reserve - Annual Meeting</label>
    </customValue>
    <customValue>
        <fullName>10006</fullName>
        <label>Reserve - Building</label>
    </customValue>
    <customValue>
        <fullName>10005</fullName>
        <label>Reserve - Operations Restricted</label>
    </customValue>
    <customValue>
        <fullName>10004</fullName>
        <label>Reserve - Operations Unrestricted</label>
    </customValue>
    <customValue>
        <fullName>10003</fullName>
        <label>Reserve - Technology</label>
    </customValue>
    <customValue>
        <fullName>10002</fullName>
        <label>With Donor Restriction</label>
    </customValue>
    <masterLabel>Restrictions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SageIntegrationService.cls
public with sharing class SageIntegrationService {

    @future(callout=true)
    public static void postProject(String json) {
        System.debug(json);
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://sage-api-proxy-zmqsyv.5sc6y6-1.usa-e2.cloudhub.io/project');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(json);

        HttpResponse res = new Http().send(req);
        System.debug(res.getBody());
        
        if (res.getStatusCode() != 201) {
            throw new CalloutException(res.getBody());
        }
    }

    @future(callout=true)
    public static void getProjects() {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://sage-api-proxy-zmqsyv.5sc6y6-1.usa-e2.cloudhub.io/project');
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/json');

        HttpResponse res = new Http().send(req);
        System.debug(res.getBody());
    }

    public static Boolean postInvoice(String invId) {
        InvoicePayload payload = new InvoicePayload();
        List<InvoiceLineItem> liList = new List<InvoiceLineItem>();

        Invoice__c inv = [
            SELECT 
                Id,
                Date__c,
                Due_Date__c,
                Description__c,
                Restrictions__c,
                Reference_Number__c,
                Customer__c,
                Customer__r.Customer_ID__c,
                (
                    SELECT
                        Amount__c,
                        Memo__c,
                        GL_Account__r.Account_Id__c,
                        Project__r.Location__c,
                        Project__r.Department__c,
                        Project__r.ProjectId__c
                    FROM
                        Invoice_Entries__r
                    WHERE 
                        Invoice__c = :invId
                )
            FROM
                Invoice__c
            WHERE
                Id = :invId
        ];

        for (Invoice_Entry__c ie : inv.Invoice_Entries__r) {
            InvoiceLineItem ili = new InvoiceLineItem();
            ili.amount = ie.Amount__c;
            ili.memo = ie.Memo__c;
            ili.glAccountNo = ie.GL_Account__r.Account_Id__c;
            ili.projectId = ie.Project__r.ProjectId__c;
            ili.locationId = ie.Project__r.Location__c;
            ili.departmentId = ie.Project__r.Department__c;
            ili.restrictionId = inv.Restrictions__c;
            liList.add(ili);
        }

        payload.salesforceId = inv.Id;
        payload.invoiceDate = inv.Date__c;
        payload.dueDate = inv.Due_Date__c;
        payload.description = inv.Description__c;
        payload.lineItem = liList;
        payload.customer = new SageCustomer(
            inv.Customer__c, 
            inv.Customer__r.Customer_ID__c
        );

        System.debug(JSON.serializePretty(payload));

        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://sage-api-proxy-zmqsyv.5sc6y6-1.usa-e2.cloudhub.io/invoice');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(JSON.serializePretty(payload));

        HttpResponse res = new Http().send(req);
        System.debug(res.getBody());
        
        if (res.getStatusCode() != 201) {
            Map<String, Object> resBody = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            throw new CalloutException((String) resBody.get('message'));
        } 

        return true;
    }

    @future(callout=true)
    public static void getInvoices() {

        Mulesoft_Connector__mdt mc = [
            SELECT Id, LastCalloutDate__c 
            FROM Mulesoft_Connector__Mdt
            WHERE DeveloperName = 'Invoice'
        ];

        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://sage-api-proxy-zmqsyv.5sc6y6-1.usa-e2.cloudhub.io/invoice?lastUpdate=' + mc.LastCalloutDate__c);
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/json');

        HttpResponse res = new Http().send(req);
    } 

    public static Boolean postPayment(String payId) {
        System.debug(payId);
        Invoice_Payment__c pay = [
            SELECT
                Id,
                Amount__c,
                Date__c,
                Payment_Type__c,
                Notes__c,
                Invoice__r.Customer__r.Customer_ID__c,
                Invoice__r.SageRecId__c
            FROM Invoice_Payment__c
            WHERE Id = :payId
        ];

        PaymentPayload payload = new PaymentPayload();
        payload.salesforceId = pay.Id;
        payload.paymentMethod = pay.Payment_Type__c;
        payload.paymentDate = pay.Date__c;
        payload.description = pay.Notes__c;
        payload.currencyz = 'USD';
        payload.customerId = pay.Invoice__r.Customer__r.Customer_ID__c;
        payload.paymentDetail = new PaymentDetail(
            pay.Invoice__r.SageRecId__c,
            pay.Amount__c
        );

        System.debug(JSON.serializePretty(new Map<String, Object>{
            'salesforceId' => payload.salesforceId,
            'paymentMethod' => payload.paymentMethod,
            'paymentDate' => String.valueOf(payload.paymentDate),
            'description' => payload.description,
            'currency' => payload.currencyz,
            'customerId' => payload.customerId,
            'paymentDetail' => payload.paymentDetail
        }));

        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://sage-api-proxy-zmqsyv.5sc6y6-1.usa-e2.cloudhub.io/payment');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(JSON.serializePretty(new Map<String, Object>{
            'salesforceId' => payload.salesforceId,
            'paymentMethod' => payload.paymentMethod,
            'paymentDate' => String.valueOf(payload.paymentDate),
            'description' => payload.description,
            'currency' => payload.currencyz,
            'customerId' => payload.customerId,
            'paymentDetail' => payload.paymentDetail
        }));

        HttpResponse res = new Http().send(req);
        System.debug(res.getBody());
        
        if (res.getStatusCode() != 201) {
            Map<String, Object> resBody = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            throw new CalloutException((String) resBody.get('message'));
        }  

        return true;
    }

    public class SageCustomer {
        public String salesforceId;
        public String customerId;

        public SageCustomer(String salesforceId, String customerId) {
            this.salesforceId = salesforceId;
            this.customerId = customerId;
        }
    }
    
    public class ProjectPayload {
        public String salesforceRecordId;
        public String projectId;
        public String projectName;
        public String projectCategory;
        public String projectType;
        public String projectStatus;
        public Boolean status;
        public String description;
        public Date startDate;
        public Date endDate;
        public String restrictionId;
        public String locationId;
        public String deptId;
        public SageCustomer customer;
    }

    public class InvoicePayload {
        public String salesforceId;
        public Date invoiceDate;
        public Date dueDate;
        public String terms;
        public String poNumber;
        public String description;
        public String billTo;
        public String shipTo;
        public SageCustomer customer;
        public InvoiceLineItem[] lineItem;
    }

    public class InvoiceLineItem {
        public String glAccountNo;
        public Decimal amount;
        public String memo;
        public String itemId;
        public String projectId;
        public String locationId;
        public String departmentId;
        public String restrictionId;
    }

    public class PaymentPayload {
        public String salesforceId;
        public String paymentMethod;
        public String customerId;
        public String description;
        public Date paymentDate;
        public String currencyz;
        public PaymentDetail paymentDetail;
    }

    public class PaymentDetail {
        public String sageInvoiceId;
        public Decimal amount;

        public PaymentDetail(String sageInvoiceId, Decimal amount) {
            this.sageInvoiceId = sageInvoiceId;
            this.amount = amount;
        }
    }
}