force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inntact_GL_Account__c/Inntact_GL_Account__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Invoice_Entry__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Entry__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Restrictions__c</fullName>
    <label>Restrictions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10008</fullName>
                <label>General Unrestricted</label>
            </value>
            <value>
                <fullName>10007</fullName>
                <label>Reserve - Annual Meeting</label>
            </value>
            <value>
                <fullName>10006</fullName>
                <label>Reserve - Building</label>
            </value>
            <value>
                <fullName>10005</fullName>
                <label>Reserve - Operations Restricted</label>
            </value>
            <value>
                <fullName>10004</fullName>
                <label>Reserve - Operations Unrestricted</label>
            </value>
            <value>
                <fullName>10003</fullName>
                <label>Reserve - Technology</label>
            </value>
            <value>
                <fullName>10002</fullName>
                <label>With Donor Restriction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/Invoice_Entry__c.object-meta.xml
<CustomObject>
    <label>Invoice Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Invoice Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Entry__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <label>GL Account</label>
    <referenceTo>Inntact_GL_Account__c</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Payment__c/Invoice_Payment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP-{MM}{YYYY}{00}</displayFormat>
        <label>Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>The Council of State Governments</label>
            </value>
            <value>
                <fullName>AAPCA</fullName>
                <label>The Association of Air Pollution Control</label>
            </value>
            <value>
                <fullName>APPA</fullName>
                <label>American Probation and Parole Association</label>
            </value>
            <value>
                <fullName>CANNRA</fullName>
                <label>Cannabis Regulators Association</label>
            </value>
            <value>
                <fullName>East</fullName>
                <label>East Region</label>
            </value>
            <value>
                <fullName>JC</fullName>
                <label>Justice Center</label>
            </value>
            <value>
                <fullName>MIC3</fullName>
                <label>Military Interstate Children&apos;s Compact C</label>
            </value>
            <value>
                <fullName>Midwest</fullName>
                <label>Midwest Region</label>
            </value>
            <value>
                <fullName>NASFA</fullName>
                <label>National Association of ST Facility Adm</label>
            </value>
            <value>
                <fullName>NASPE</fullName>
                <label>National Association of ST Pers Exec</label>
            </value>
            <value>
                <fullName>NASPTD</fullName>
                <label>National Association of ST Tech Director</label>
            </value>
            <value>
                <fullName>NATL</fullName>
                <label>National</label>
            </value>
            <value>
                <fullName>NATL HQ</fullName>
                <label>National Headquarters</label>
            </value>
            <value>
                <fullName>NEMA</fullName>
                <label>National Emergency Mgmt Association</label>
            </value>
            <value>
                <fullName>NHCSL</fullName>
                <label>National Hispanic Caucus of ST Legis</label>
            </value>
            <value>
                <fullName>SIDO</fullName>
                <label>State International Development Orgs</label>
            </value>
            <value>
                <fullName>South</fullName>
                <label>South Region</label>
            </value>
            <value>
                <fullName>West</fullName>
                <label>West Region</label>
            </value>
            <value>
                <fullName>WIG</fullName>
                <label>Women in Government</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCategory__c.field-meta.xml
<CustomField>
    <fullName>ProjectCategory__c</fullName>
    <label>Project Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Internal Non-billable</fullName>
            </value>
            <value>
                <fullName>Internal Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectStatus__c.field-meta.xml
<CustomField>
    <fullName>ProjectStatus__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Awaiting PO</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Service</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Host State Meetings</fullName>
            </value>
            <value>
                <fullName>Junk Dump</fullName>
            </value>
            <value>
                <fullName>Lobbying</fullName>
            </value>
            <value>
                <fullName>Meetings</fullName>
            </value>
            <value>
                <fullName>Other Restricted</fullName>
            </value>
            <value>
                <fullName>Publications</fullName>
            </value>
            <value>
                <fullName>Special Projects</fullName>
            </value>
            <value>
                <fullName>Task Force</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Restrictions__c</fullName>
    <label>Restrictions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Restrictions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <businessProcess>Grants</businessProcess>
    <label>Grant</label>
</RecordType>

force-app/main/default/globalValueSets/Restrictions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10008</fullName>
        <label>General Unrestricted</label>
    </customValue>
    <customValue>
        <fullName>10007</fullName>
        <label>Reserve - Annual Meeting</label>
    </customValue>
    <customValue>
        <fullName>10006</fullName>
        <label>Reserve - Building</label>
    </customValue>
    <customValue>
        <fullName>10005</fullName>
        <label>Reserve - Operations Restricted</label>
    </customValue>
    <customValue>
        <fullName>10004</fullName>
        <label>Reserve - Operations Unrestricted</label>
    </customValue>
    <customValue>
        <fullName>10003</fullName>
        <label>Reserve - Technology</label>
    </customValue>
    <customValue>
        <fullName>10002</fullName>
        <label>With Donor Restriction</label>
    </customValue>
    <masterLabel>Restrictions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SageIntegrationServiceTest.cls
@isTest
public with sharing class SageIntegrationServiceTest {

    static final Map<String, HttpResponse> resStore = new Map<String, HttpResponse>{
        'postSuccess' => HttpResponseFactory.postSuccess(),
        'postFailure' => HttpResponseFactory.postFailure(),
        'getSuccess' => HttpResponseFactory.getSuccess(),
        'getFailure' => HttpResponseFactory.getFailure()
    };

    static final List<HttpMatchingStrategy> matchers = new List<HttpMatchingStrategy>{
        new HttpResponseMatchers.PostMatcher(),
        new HttpResponseMatchers.GetMatcher()
    };

    @isTest
    static void postProjectSuccess() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            true
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        Test.startTest();
        opp.StageName = 'Closed Won';
        update opp;
        Test.stopTest();
    }

    @isTest
    static void postProjectFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        try {
            Test.startTest();
            opp.StageName = 'Closed Won';
            update opp; 
            Test.stopTest();
        }
        catch (CalloutException ex) {
            System.debug(ex.getMessage());
            Assert.isNotNull(ex.getMessage(), 'An exception was not thrown.');
        }
    }

    @isTest
    static void getProjectSuccess() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            true
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Test.startTest();
        SageIntegrationService.getProjects();
        Test.stopTest();
    }

    @isTest
    static void getProjectFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);

        try {
            Test.startTest();
            SageIntegrationService.getProjects();
            Test.stopTest();
        }
        catch (CalloutException ex) {
            System.debug(ex.getMessage());
            Assert.isNotNull(ex.getMessage(), 'An exception was not thrown.');
        } 
    }

    @isTest
    static void postInvoiceSuccess() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            true
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Inntact_GL_Account__c glAcc = new Inntact_GL_Account__c(
            Name = 'Dues',
            Account_Id__c = '40010'
        );
        insert glAcc;
        
        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        Invoice__c inv = new Invoice__c(
            Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(30),
            Restrictions__c = '10008',
            Customer__c = acc.Id
        );
        insert inv;

        Invoice_Entry__c ie = new Invoice_Entry__c(
            Amount__c = 1000.45,
            GL_Account__c = glAcc.Id,
            Project__c = opp.Id,
            Invoice__c = inv.Id
        );
        insert ie;

        Test.startTest();
        Assert.isTrue(SyncInvoiceActionHandler.sendInvoiceToSage(inv.Id), 'The callout was not successful.');
        Test.stopTest();
    }

    @isTest
    static void postInvoiceNoLineItemFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);
        
        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Invoice__c inv = new Invoice__c(
            Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(30),
            Restrictions__c = '10008',
            Customer__c = acc.Id
        );
        insert inv;

        Boolean success;
        try {
            Test.startTest();
            success = SyncInvoiceActionHandler.sendInvoiceToSage(inv.Id);
            Test.stopTest();
        }
        catch (Exception ex) {
            Assert.isNotNull(ex.getMessage(), 'Invoice synced successfully without Line Items');
        }
    }

    @isTest
    static void postInvoiceFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Inntact_GL_Account__c glAcc = new Inntact_GL_Account__c(
            Name = 'Dues',
            Account_Id__c = '40010'
        );
        insert glAcc;
        
        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        Invoice__c inv = new Invoice__c(
            Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(30),
            Restrictions__c = '10008',
            Customer__c = acc.Id
        );
        insert inv;

        Invoice_Entry__c ie = new Invoice_Entry__c(
            Amount__c = 1000.45,
            GL_Account__c = glAcc.Id,
            Project__c = opp.Id,
            Invoice__c = inv.Id
        );
        insert ie;

        Boolean success;
        try {
            Test.startTest();
            success = SyncInvoiceActionHandler.sendInvoiceToSage(inv.Id);
            Test.stopTest();
        }
        catch (Exception ex) {
            Assert.isNotNull(ex.getMessage(), 'Invoice synced successfully with a bad request.');
        }
    }

    @isTest
    static void getInvoiceSuccess() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            true
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Test.startTest();
        SageIntegrationService.getInvoices();
        Test.stopTest();
    }

    @isTest
    static void getInvoiceFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);

        try {
            Test.startTest();
            SageIntegrationService.getInvoices();
            Test.stopTest();
        }
        catch (CalloutException ex) {
            System.debug(ex.getMessage());
            Assert.isNotNull(ex.getMessage(), 'An exception was not thrown.');
        } 
    } 

    @isTest
    static void postPaymentSuccess() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            true
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Inntact_GL_Account__c glAcc = new Inntact_GL_Account__c(
            Name = 'Dues',
            Account_Id__c = '40010'
        );
        insert glAcc;
        
        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        Invoice__c inv = new Invoice__c(
            Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(30),
            Restrictions__c = '10008',
            Customer__c = acc.Id,
            State__c = 'Posted'
        );
        insert inv;

        Invoice_Entry__c ie = new Invoice_Entry__c(
            Amount__c = 1000.45,
            GL_Account__c = glAcc.Id,
            Project__c = opp.Id,
            Invoice__c = inv.Id
        );
        insert ie;

        Invoice_Payment__c pay = new Invoice_Payment__c(
            Date__c = Date.today(),
            Payment_Type__c = 'Cash',
            Invoice__c = inv.Id
        );
        insert pay;


        Test.startTest();
        Boolean success = SyncInvoiceActionHandler.sendPaymentToSage(pay.Id);
        Test.stopTest();

        Assert.isTrue(success, 'The callout was not successful.'); 
    }

    @isTest
    static void postPaymentDraftInvoiceFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Inntact_GL_Account__c glAcc = new Inntact_GL_Account__c(
            Name = 'Dues',
            Account_Id__c = '40010'
        );
        insert glAcc;
        
        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        Invoice__c inv = new Invoice__c(
            Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(30),
            Restrictions__c = '10008',
            Customer__c = acc.Id,
            State__c = 'Draft'
        );
        insert inv;

        Invoice_Entry__c ie = new Invoice_Entry__c(
            Amount__c = 1000.45,
            GL_Account__c = glAcc.Id,
            Project__c = opp.Id,
            Invoice__c = inv.Id
        );
        insert ie;

        Invoice_Payment__c pay = new Invoice_Payment__c(
            Date__c = Date.today(),
            Payment_Type__c = 'Cash',
            Invoice__c = inv.Id
        );
        insert pay;


        try {
            Test.startTest();
            Boolean success = SyncInvoiceActionHandler.sendPaymentToSage(pay.Id);
            Test.stopTest(); 
        }
        catch (Exception ex) {
            Assert.isNotNull(ex.getMessage(), 'Payment sent to sage while the invoice is in a draft state.');  
        }
    }

    @isTest
    static void postPaymentFailure() {
        MockMultiHttpResponseGenerator mock = new MockMultiHttpResponseGenerator(
            resStore, 
            matchers, 
            false
        );
        Test.setMock(HttpCalloutMock.class, mock);

        Inntact_GL_Account__c glAcc = new Inntact_GL_Account__c(
            Name = 'Dues',
            Account_Id__c = '40010'
        );
        insert glAcc;
        
        Account acc = new Account(
            Name = 'Test Cust',
            Customer_ID__c = '12345'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Follow Up',
            CloseDate = Date.today(),
            Description = 'This is a test',
            Active__c = true,
            ProjectStatus__c = 'Active',
            ProjectType__c = 'Other Restricted',
            ProjectCategory__c = 'Internal Non-billable',
            Location__c = 'NATL',
            Department__c = 'ADM',
            Restrictions__c = '10008',
            Start_Date__c = Date.today(),
            EndDate__c = Date.today().addDays(30),
            AccountId = acc.Id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id
        );
        insert opp;

        Invoice__c inv = new Invoice__c(
            Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(30),
            Restrictions__c = '10008',
            Customer__c = acc.Id,
            State__c = 'Posted'
        );
        insert inv;

        Invoice_Entry__c ie = new Invoice_Entry__c(
            Amount__c = 1000.45,
            GL_Account__c = glAcc.Id,
            Project__c = opp.Id,
            Invoice__c = inv.Id
        );
        insert ie;

        Invoice_Payment__c pay = new Invoice_Payment__c(
            Date__c = Date.today(),
            Payment_Type__c = 'Cash',
            Invoice__c = inv.Id
        );
        insert pay;


        try {
            Test.startTest();
            Boolean success = SyncInvoiceActionHandler.sendPaymentToSage(pay.Id);
            Test.stopTest(); 
        }
        catch (Exception ex) {
            Assert.isNotNull(ex.getMessage(), 'Payment synced with sage with a bad request.');  
        }
    }



}