force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>The Council of State Governments</label>
            </value>
            <value>
                <fullName>AAPCA</fullName>
                <label>The Association of Air Pollution Control</label>
            </value>
            <value>
                <fullName>APPA</fullName>
                <label>American Probation and Parole Association</label>
            </value>
            <value>
                <fullName>CANNRA</fullName>
                <label>Cannabis Regulators Association</label>
            </value>
            <value>
                <fullName>East</fullName>
                <label>East Region</label>
            </value>
            <value>
                <fullName>JC</fullName>
                <label>Justice Center</label>
            </value>
            <value>
                <fullName>MIC3</fullName>
                <label>Military Interstate Children&apos;s Compact C</label>
            </value>
            <value>
                <fullName>Midwest</fullName>
                <label>Midwest Region</label>
            </value>
            <value>
                <fullName>NASFA</fullName>
                <label>National Association of ST Facility Adm</label>
            </value>
            <value>
                <fullName>NASPE</fullName>
                <label>National Association of ST Pers Exec</label>
            </value>
            <value>
                <fullName>NASPTD</fullName>
                <label>National Association of ST Tech Director</label>
            </value>
            <value>
                <fullName>NATL</fullName>
                <label>National</label>
            </value>
            <value>
                <fullName>NATL HQ</fullName>
                <label>National Headquarters</label>
            </value>
            <value>
                <fullName>NEMA</fullName>
                <label>National Emergency Mgmt Association</label>
            </value>
            <value>
                <fullName>NHCSL</fullName>
                <label>National Hispanic Caucus of ST Legis</label>
            </value>
            <value>
                <fullName>SIDO</fullName>
                <label>State International Development Orgs</label>
            </value>
            <value>
                <fullName>South</fullName>
                <label>South Region</label>
            </value>
            <value>
                <fullName>West</fullName>
                <label>West Region</label>
            </value>
            <value>
                <fullName>WIG</fullName>
                <label>Women in Government</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCategory__c.field-meta.xml
<CustomField>
    <fullName>ProjectCategory__c</fullName>
    <label>Project Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Internal Non-billable</fullName>
            </value>
            <value>
                <fullName>Internal Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <label>Project Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectStatus__c.field-meta.xml
<CustomField>
    <fullName>ProjectStatus__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Awaiting PO</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Service</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Host State Meetings</fullName>
            </value>
            <value>
                <fullName>Junk Dump</fullName>
            </value>
            <value>
                <fullName>Lobbying</fullName>
            </value>
            <value>
                <fullName>Meetings</fullName>
            </value>
            <value>
                <fullName>Other Restricted</fullName>
            </value>
            <value>
                <fullName>Publications</fullName>
            </value>
            <value>
                <fullName>Special Projects</fullName>
            </value>
            <value>
                <fullName>Task Force</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Restrictions__c</fullName>
    <label>Restrictions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Restrictions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <businessProcess>Grants</businessProcess>
    <label>Grant</label>
</RecordType>

force-app/main/default/globalValueSets/Restrictions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10008</fullName>
        <label>General Unrestricted</label>
    </customValue>
    <customValue>
        <fullName>10007</fullName>
        <label>Reserve - Annual Meeting</label>
    </customValue>
    <customValue>
        <fullName>10006</fullName>
        <label>Reserve - Building</label>
    </customValue>
    <customValue>
        <fullName>10005</fullName>
        <label>Reserve - Operations Restricted</label>
    </customValue>
    <customValue>
        <fullName>10004</fullName>
        <label>Reserve - Operations Unrestricted</label>
    </customValue>
    <customValue>
        <fullName>10003</fullName>
        <label>Reserve - Technology</label>
    </customValue>
    <customValue>
        <fullName>10002</fullName>
        <label>With Donor Restriction</label>
    </customValue>
    <masterLabel>Restrictions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityService.cls
public with sharing class OpportunityService {
    
    public static void syncProject(List<Opportunity> oppList, Map<Id, Opportunity> oldOppMap) {
        String rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grant' AND SObjectType = 'Opportunity'].Id;
        for (Opportunity opp : oppList) {
            if (opp.StageName == 'Closed Won' & 
                String.isEmpty(opp.ProjectId__c) & 
                oldOppMap.get(opp.Id).StageName != opp.StageName &
                opp.RecordTypeId == rtId) {
                Account acc = [
                    SELECT Id, Customer_ID__c 
                    FROM Account 
                    WHERE Id = :opp.AccountId
                ];

                SageIntegrationService.SageCustomer cust = new SageIntegrationService.SageCustomer(
                    acc.Id,
                    acc?.Customer_ID__c
                );

                SageIntegrationService.ProjectPayload proj = new SageIntegrationService.ProjectPayload();
                proj.salesforceRecordId = opp.Id;
                proj.projectName = opp.Name;
                proj.projectCategory = opp.ProjectCategory__c;
                proj.projectType = opp.ProjectType__c;
                proj.projectStatus = opp.ProjectStatus__c;
                proj.status = opp.Active__c;
                proj.description = opp.Description;
                proj.startDate = opp.Start_Date__c;
                proj.endDate = opp.EndDate__c;
                proj.restrictionId = opp.Restrictions__c;
                proj.locationId = opp.Location__c;
                proj.deptId = opp.Department__c;
                proj.customer = cust;

                // * MAKE CALLOUT
                SageIntegrationService.postProject(JSON.serializePretty(proj));
            }
        }
    }
}