force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Entry__c/Invoice_Entry__c.object-meta.xml
<CustomObject>
    <label>Invoice Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Invoice Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Entry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Entries</relationshipLabel>
    <relationshipName>Invoice_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Payment__c/Invoice_Payment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP-{MM}{YYYY}{00}</displayFormat>
        <label>Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SyncInvoiceActionHandler.cls
public with sharing class SyncInvoiceActionHandler {
    
    @AuraEnabled
    public static Boolean sendInvoiceToSage(String id) {
        Invoice_Entry__c[] ieList = [SELECT Id FROM Invoice_Entry__c WHERE Invoice__c = :id];

        if (ieList.size() == 0) {
            throw new AuraHandledException('You need to have at least one invoice entry to sync an invoice to Sage');
        } else {
            return SageIntegrationService.postInvoice(id);
        }

    }

    @AuraEnabled
    public static Boolean sendPaymentToSage(String id){
        Invoice_Payment__c pay = [
            SELECT Invoice__r.State__c 
            FROM Invoice_Payment__c 
            WHERE Id = :id
        ];

        if (pay.Invoice__r.State__c == 'Draft') {
            throw new AuraHandledException('To sync/apply payments to an invoice, the invoice must be in a Posted state.');
        } else {
            return SageIntegrationService.postPayment(id);
        }
    }
}